baseURL : "https://xugr.me/hugo-water/"
languageCode : "en-us"
title : "Hugo - Water"
theme : "hugo-water"
themesDir : "../../"

params:
  copyright: "Made by Ray Xu with ❤️️"
  social:
  - name: GitHub
    url: https://github.com/megrxu
  - name: RSS
    url: index.xml


menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: post
    name: Posts
    url: /post/
    weight: 1
  - identifier: links
    name: Links
    weight: 2
  - identifier: github
    name: GitHub
    url: https://github.com
    weight: 1
    parent: links